#!/usr/bin/env python3
"""Installer for Vertex.

Copies the app to a permanent home, gives it a virtualenv of its own, and
registers it with the desktop so it appears in the start menu.

    ~/.local/lib/vertex/app/     the program — main.py, src/, Assets/
    ~/.local/lib/vertex/venv/    its dependencies, kept across upgrades
    ~/.local/bin/vertex          the launcher

The clone you run this from is only the source: once installed, the app no
longer reads anything out of it, so the checkout can be moved, updated or
deleted without breaking the start-menu entry. Re-run this script to upgrade
an existing install — only the `app/` folder is replaced, and it is swapped in
whole, so an interrupted upgrade leaves the previous version running.

**Nothing the user owns is ever written to.** Your config, your library, your
thumbnail cache, your clips and your exports are read to report on them and
otherwise left exactly as they are; an existing install is never asked to
migrate anything. Removing them is a separate, manual act, and --uninstall
prints the commands rather than running them.

    python install.py              install or upgrade, and add to the start menu
    python install.py --check      only report on the requirements
    python install.py --reset-config   re-run first-run setup on next launch
    python install.py --uninstall  remove the program, keeping all your data
"""

import argparse
import ctypes
import ctypes.util
import json
import os
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field

PY_MIN = (3, 10)

HERE = os.path.dirname(os.path.abspath(__file__))
APP_NAME = "Vertex"
APP_ID = "vertex"
APP_SLUG = "vertex"

# What gets copied into the install. docs/ and the screenshots are not part of
# the running app, so they stay in the checkout.
PAYLOAD = ("main.py", "src", "Assets", "requirements.txt", "LICENSE")
COPY_IGNORE = shutil.ignore_patterns("__pycache__", "*.py[cod]", ".venv", "venv")

# Program files go under ~/.local/lib rather than ~/.local/share, because
# ~/.local/share/vertex is the *data* directory's default — the library would
# end up inside the folder an upgrade replaces.
DEFAULT_PREFIX = os.path.expanduser("~/.local/lib")
BIN_DIR = os.path.expanduser("~/.local/bin")
LAUNCHER = os.path.join(BIN_DIR, APP_ID)
# Written into the launcher so --uninstall can tell our script from a file of
# the same name that somebody else put there.
LAUNCHER_MARK = "# generated by the Vertex installer"

# App IDs this installer has registered before. Their entries and icons are
# removed alongside the current ones, so a rename leaves one launcher in the
# start menu rather than the new one beside a stale Vertex Moments.
LEGACY_APP_IDS = ("vertex-moments", "grapheneseries-moments")

DESKTOP_DIR = os.path.expanduser("~/.local/share/applications")
DESKTOP_FILE = os.path.join(DESKTOP_DIR, f"{APP_ID}.desktop")
ICON_ROOT = os.path.expanduser("~/.local/share/icons/hicolor")
ICON_SIZES = (512, 256, 128, 64, 48, 32, 24, 16)

CONFIG_DIR = os.path.expanduser(f"~/.config/{APP_SLUG}")
CONFIG_PATH = os.path.join(CONFIG_DIR, "config.json")

# XDG homes for a fresh install. An existing config names its own — possibly
# under one of the older slugs below — and those are what get used instead.
XDG_DIRS = [
    CONFIG_DIR,
    os.path.expanduser(f"~/.local/share/{APP_SLUG}"),
    os.path.expanduser(f"~/.local/state/{APP_SLUG}"),
    os.path.expanduser(f"~/.cache/{APP_SLUG}"),
]

# Directory names the app has stored data under before the renames. Listed so
# the installer can find a library that is still living under one and report
# it as in use — never to move it.
LEGACY_SLUGS = ("vertex_moments", "grapheneseries_moments",
                "graphene_series_moments")

# Config keys that name a folder full of the user's own files.
PATH_KEYS = ("clip_path", "export_path", "data_path", "state_path", "cache_path")

OK, MISSING, OPTIONAL = "\033[32m✓\033[0m", "\033[31m✗\033[0m", "\033[33m○\033[0m"
BOLD, DIM, RESET = "\033[1m", "\033[2m", "\033[0m"


def plain(text):
    """Strip the colour codes, for when output is not going to a terminal."""
    for code in (OK, MISSING, OPTIONAL, BOLD, DIM, RESET):
        text = text.replace(code, {OK: "OK", MISSING: "!!", OPTIONAL: "--"}.get(code, ""))
    return text


def say(text=""):
    print(text if sys.stdout.isatty() else plain(text))


def tilde(path):
    """Shorten a path under $HOME for display."""
    home = os.path.expanduser("~")
    if path == home or path.startswith(home + os.sep):
        return "~" + path[len(home):]
    return path


def human(size):
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if size < 1024 or unit == "TB":
            return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
        size /= 1024


# --- Where things go -------------------------------------------------------
@dataclass
class Install:
    """The layout of one installation, rooted at `root`.

    `app` is replaced wholesale by an upgrade; `venv` deliberately sits outside
    it so the dependencies survive one, and `manifest` marks the root as ours —
    --uninstall will not delete a directory that does not carry it.
    """

    root: str
    use_venv: bool = True
    # Set only by --no-venv: the interpreter to launch with instead.
    external_python: str = ""

    @property
    def app(self):
        return os.path.join(self.root, "app")

    @property
    def venv(self):
        return os.path.join(self.root, "venv")

    @property
    def manifest(self):
        return os.path.join(self.root, ".vertex-install.json")

    @property
    def entry_point(self):
        return os.path.join(self.app, "main.py")

    @property
    def python(self):
        """The interpreter the launcher will run the app with."""
        if not self.use_venv:
            return self.external_python or sys.executable
        return os.path.join(self.venv, "bin", "python")

    @property
    def installed(self):
        return os.path.exists(self.manifest)

    def read_manifest(self):
        try:
            with open(self.manifest) as handle:
                return json.load(handle)
        except (OSError, ValueError):
            return {}

    def logo(self, variant):
        """The desktop icon source, taken from the installed copy.

        The icon is scaled from artwork inside the install rather than out of
        the checkout, so the file the theme was built from is one that stays
        put.
        """
        return os.path.join(self.app, "Assets", "logo", variant,
                            f"{APP_ID}-mark-{variant}.png")


def base_python():
    """The interpreter to build the app's virtualenv from.

    When this script is itself running inside a virtualenv, that venv's python
    is a thin shim over a real installation; building from the real one keeps
    the app's environment independent of a checkout-local venv that may be
    deleted the moment the clone is.
    """
    candidate = getattr(sys, "_base_executable", "") or ""
    if candidate and os.path.isfile(candidate):
        return candidate
    return sys.executable


# --- Requirements ----------------------------------------------------------
@dataclass
class Requirement:
    """One thing the app needs, and how to obtain it on the running distro.

    Exactly one of `module`, `binary` or `library` says how to look for it:
    a Python module imported by a named interpreter, an executable on PATH, or
    a shared library the dynamic loader can find.
    """

    label: str
    module: str = ""
    binary: str = ""
    library: tuple = ()                            # candidate soname(s)
    required: bool = True
    note: str = ""                                 # what an optional one adds
    pip: str = ""                                  # pip distribution name
    system: dict = field(default_factory=dict)     # distro family -> package

    def check(self, python=None):
        """Returns (ok, detail) — detail explains a failure or names a version.

        `python` picks the interpreter a module is imported by. None means this
        one, which is what the pre-flight pass wants; the verification pass
        after the install passes the app's own interpreter, because a package
        installed for a *different* Python is exactly the failure this is meant
        to catch.
        """
        if self.module:
            if python and os.path.abspath(python) != os.path.abspath(sys.executable):
                return probe_module(python, self.module)
            try:
                mod = __import__(self.module)
            except ImportError as err:
                return False, str(err)
            except OSError as err:
                # python-mpv imports fine but loads libmpv at import time.
                return False, f"{type(err).__name__}: {err}"
            return True, str(getattr(mod, "__version__", ""))
        if self.library:
            return check_library(self.library)
        found = shutil.which(self.binary)
        return bool(found), found or f"{self.binary} not on PATH"


def probe_module(python, module):
    """Import `module` with another interpreter. Returns (ok, detail)."""
    code = ("import importlib, sys\n"
            "m = importlib.import_module(sys.argv[1])\n"
            "print(getattr(m, '__version__', ''))\n")
    try:
        done = subprocess.run([python, "-c", code, module],
                              capture_output=True, text=True, timeout=120)
    except (OSError, subprocess.SubprocessError) as err:
        return False, str(err)
    if done.returncode == 0:
        return True, done.stdout.strip()
    lines = [line for line in done.stderr.strip().splitlines() if line.strip()]
    return False, lines[-1] if lines else "import failed"


def check_library(sonames):
    """Look for a shared library the way python-mpv will at import time."""
    for soname in sonames:
        try:
            ctypes.CDLL(soname)
            return True, soname
        except OSError:
            continue
    found = ctypes.util.find_library(sonames[0].split(".so")[0].removeprefix("lib"))
    if found:
        return True, found
    return False, f"{sonames[0]} not found by the dynamic loader"


# Things pip cannot supply: they come from the distro, and are checked before
# anything is copied, because no amount of installing will conjure them up.
SYSTEM_REQUIREMENTS = [
    Requirement("Tk (tkinter)", module="tkinter",
                system={"arch": "tk", "debian": "python3-tk",
                        "fedora": "python3-tkinter", "suse": "python3-tk"}),
    Requirement("libmpv", library=("libmpv.so.2", "libmpv.so.1", "libmpv.so"),
                system={"arch": "mpv", "debian": "libmpv2",
                        "fedora": "mpv-libs", "suse": "libmpv2"}),
    Requirement("ffmpeg", binary="ffmpeg",
                system={"arch": "ffmpeg", "debian": "ffmpeg",
                        "fedora": "ffmpeg", "suse": "ffmpeg"}),
    Requirement("ffprobe", binary="ffprobe",
                system={"arch": "ffmpeg", "debian": "ffmpeg",
                        "fedora": "ffmpeg", "suse": "ffmpeg"}),
    Requirement("xdg-user-dir", binary="xdg-user-dir", required=False,
                note="detecting your localized Videos folder during setup",
                system={"arch": "xdg-user-dirs", "debian": "xdg-user-dirs",
                        "fedora": "xdg-user-dirs", "suse": "xdg-user-dirs"}),
    Requirement("xdg-open", binary="xdg-open", required=False,
                note="the “Show in files” action opening your file manager",
                system={"arch": "xdg-utils", "debian": "xdg-utils",
                        "fedora": "xdg-utils", "suse": "xdg-utils"}),
]

# Things the installer puts into the app's virtualenv itself. These are not a
# reason to stop before copying — they are what the install step is for.
PIP_REQUIREMENTS = [
    Requirement("CustomTkinter", module="customtkinter", pip="customtkinter"),
    Requirement("Pillow", module="PIL", pip="Pillow"),
    Requirement("python-mpv", module="mpv", pip="python-mpv"),
    Requirement("Send2Trash", module="send2trash", required=False,
                note="sending deleted clips to the Trash instead of erasing them",
                pip="Send2Trash"),
]

INSTALLERS = {
    "arch": "sudo pacman -S --needed",
    "debian": "sudo apt install",
    "fedora": "sudo dnf install",
    "suse": "sudo zypper install",
}


def distro_family():
    """'arch' | 'debian' | 'fedora' | 'suse' | '', read from /etc/os-release."""
    fields = {}
    try:
        with open("/etc/os-release") as handle:
            for line in handle:
                key, _, value = line.strip().partition("=")
                fields[key] = value.strip('"')
    except OSError:
        return ""
    names = [fields.get("ID", "")] + fields.get("ID_LIKE", "").split()
    for name in names:
        if name in INSTALLERS:
            return name
        if name in ("cachyos", "manjaro", "endeavouros"):
            return "arch"
        if name in ("ubuntu", "linuxmint", "pop"):
            return "debian"
        if name in ("rhel", "centos"):
            return "fedora"
    return ""


def check_python():
    """Report on the interpreter version. Returns True when it is new enough."""
    version = ".".join(str(part) for part in sys.version_info[:3])
    if sys.version_info >= PY_MIN:
        say(f"  {OK} Python {version}")
        return True
    need = ".".join(str(part) for part in PY_MIN)
    say(f"  {MISSING} Python {version} — {need} or newer required")
    return False


def check_requirements(requirements, python=None, heading="Requirements"):
    """Print one requirements table. Returns (missing_required, missing_optional)."""
    say(f"{BOLD}{heading}{RESET}")
    if python:
        say(f"  {DIM}checked against {tilde(python)}{RESET}")

    missing_required, missing_optional = [], []
    for req in requirements:
        ok, detail = req.check(python)
        if ok:
            say(f"  {OK} {req.label}" + (f" {DIM}{detail}{RESET}" if detail else ""))
        elif req.required:
            missing_required.append(req)
            say(f"  {MISSING} {req.label} {DIM}— {detail}{RESET}")
        else:
            missing_optional.append(req)
            say(f"  {OPTIONAL} {req.label} {DIM}— optional; adds {req.note}{RESET}")
    return missing_required, missing_optional


def report_fixes(missing, family):
    """Print the distro commands that would satisfy `missing`."""
    packages = [req.system[family] for req in missing
                if family and family in req.system]
    if not packages:
        return
    say()
    say(f"{BOLD}To install those{RESET}")
    # One package can cover two rows (ffmpeg/ffprobe); list it once.
    say(f"  {INSTALLERS[family]} {' '.join(dict.fromkeys(packages))}")


# --- The user's own data ---------------------------------------------------
def read_config():
    """The saved config as a dict, or {} if there is none to read."""
    try:
        with open(CONFIG_PATH) as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def configured_paths(config):
    """Every folder the config names, absolute, in the order they are listed."""
    paths = []
    for key in PATH_KEYS:
        value = config.get(key)
        if isinstance(value, str) and value.strip():
            paths.append(os.path.abspath(os.path.expanduser(value)))
    return paths


def legacy_data_dirs():
    """Data directories left under the app's earlier names that still exist."""
    found = []
    for slug in LEGACY_SLUGS:
        for base in ("~/.local/share", "~/.config", "~/.local/state", "~/.cache"):
            path = os.path.expanduser(f"{base}/{slug}")
            if os.path.isdir(path):
                found.append(path)
    return found


def report_user_data(config):
    """Show what of the user's already exists, and state that it is kept.

    Purely informational — the installer's job stops at the program, and this
    section is here so that is visible rather than merely promised.
    """
    say()
    say(f"{BOLD}Your data{RESET}")
    say(f"  {DIM}read to report on it here; never written, moved or "
        f"overwritten{RESET}")

    if not config:
        say(f"  {OPTIONAL} no config yet {DIM}— the first launch runs setup{RESET}")
        return

    say(f"  {OK} config {DIM}{tilde(CONFIG_PATH)}{RESET}")
    data_dir = config.get("data_path", "")
    if data_dir:
        library = os.path.join(os.path.expanduser(data_dir), "library.db")
        if os.path.exists(library):
            size = human(os.path.getsize(library))
            say(f"  {OK} library {DIM}{tilde(library)} · {size}{RESET}")
        else:
            say(f"  {OPTIONAL} library {DIM}not created yet · "
                f"{tilde(os.path.expanduser(data_dir))}{RESET}")
    for key in ("clip_path", "export_path", "cache_path"):
        value = config.get(key)
        if value:
            say(f"  {OK} {key.replace('_path', ''):<7} {DIM}{tilde(os.path.expanduser(value))}{RESET}")

    # A library still sitting under one of the old names is normal and fine —
    # the config points at it and the app reads it there. Saying so avoids the
    # impression that an install under the new name has stranded it.
    stale = [path for path in legacy_data_dirs()
             if path not in configured_paths(config)]
    if stale:
        say(f"  {DIM}also on disk, from earlier names of the app "
            f"(left alone):{RESET}")
        for path in stale:
            say(f"    {DIM}{tilde(path)}{RESET}")


def guard_paths(install, config):
    """Refuse to install on top of anything that is not ours.

    The install root is emptied and replaced by an upgrade, so it must not be,
    contain, or sit inside a folder holding the user's own files.
    """
    root = os.path.abspath(install.root)
    protected = {CONFIG_DIR, *XDG_DIRS[1:], *configured_paths(config),
                 *legacy_data_dirs(), os.path.expanduser("~")}
    for path in sorted(protected):
        if not path:
            continue
        if root == path:
            return f"{tilde(root)} is where your own files live"
        if root.startswith(path + os.sep) and path != os.path.expanduser("~"):
            return f"{tilde(root)} is inside {tilde(path)}, which holds your own files"
        if path.startswith(root + os.sep):
            return f"{tilde(root)} contains {tilde(path)}, which holds your own files"
    if HERE == root or HERE.startswith(root + os.sep):
        return (f"the source checkout is inside {tilde(root)} — installing would "
                f"replace the folder it is being copied from")
    if os.path.isdir(root) and os.listdir(root) and not install.installed:
        return (f"{tilde(root)} already exists and was not created by this "
                f"installer — refusing to overwrite it")
    return ""


# --- Copying the program in ------------------------------------------------
def check_payload():
    """Make sure the checkout has everything before anything is copied."""
    missing = [name for name in PAYLOAD if not os.path.exists(os.path.join(HERE, name))]
    return missing


def install_payload(install):
    """Copy the app into place, replacing any previous copy atomically.

    Staged beside the destination and swapped in with a rename, so a copy that
    fails or is interrupted leaves the version that was already installed
    running rather than half of a new one.
    """
    say()
    say(f"{BOLD}Program files{RESET}")

    staging = install.app + ".new"
    retired = install.app + ".old"
    for leftover in (staging, retired):
        shutil.rmtree(leftover, ignore_errors=True)

    try:
        os.makedirs(install.root, exist_ok=True)
        os.makedirs(staging, exist_ok=True)
        for name in PAYLOAD:
            source = os.path.join(HERE, name)
            target = os.path.join(staging, name)
            if os.path.isdir(source):
                shutil.copytree(source, target, ignore=COPY_IGNORE)
            else:
                shutil.copy2(source, target)
    except OSError as err:
        shutil.rmtree(staging, ignore_errors=True)
        say(f"  {MISSING} could not stage the copy {DIM}— {err}{RESET}")
        return False

    had_previous = os.path.isdir(install.app)
    try:
        if had_previous:
            os.replace(install.app, retired)
        os.replace(staging, install.app)
    except OSError as err:
        # Put the working copy back before giving up.
        if had_previous and not os.path.isdir(install.app):
            try:
                os.replace(retired, install.app)
            except OSError:
                pass
        shutil.rmtree(staging, ignore_errors=True)
        say(f"  {MISSING} could not swap the new copy in {DIM}— {err}{RESET}")
        return False

    shutil.rmtree(retired, ignore_errors=True)
    verb = "replaced" if had_previous else "installed"
    say(f"  {OK} {verb} {DIM}{tilde(install.app)}{RESET}")
    say(f"  {OK} copied from {DIM}{tilde(HERE)}{RESET}")
    return True


def write_manifest(install):
    """Record what this install is, so an upgrade or removal can recognise it."""
    data = {
        "app": APP_ID,
        "layout": 1,
        "installed_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "source": HERE,
        "python": install.python,
        "venv": install.use_venv,
        "payload": list(PAYLOAD),
    }
    try:
        with open(install.manifest, "w") as handle:
            json.dump(data, handle, indent=2)
    except OSError as err:
        say(f"  {OPTIONAL} could not write {tilde(install.manifest)} {DIM}— "
            f"{err}{RESET}")


# --- The app's virtualenv --------------------------------------------------
def venv_is_usable(install):
    """True when the existing venv still runs and matches the base Python.

    A distro Python upgrade leaves a venv pointing at a stdlib that is no
    longer there, which surfaces as an import error at launch rather than
    anything obvious, so it is rebuilt instead of reused.
    """
    if not os.path.exists(install.python):
        return False
    ok, detail = probe_module(install.python, "sys")
    if not ok:
        return False
    want = ".".join(str(part) for part in sys.version_info[:2])
    try:
        done = subprocess.run(
            [install.python, "-c",
             "import sys; print('.'.join(map(str, sys.version_info[:2])))"],
            capture_output=True, text=True, timeout=60)
    except (OSError, subprocess.SubprocessError):
        return False
    return done.returncode == 0 and done.stdout.strip() == want


def build_venv(install, recreate=False):
    """Create or reuse the app's virtualenv. Returns False on failure."""
    say()
    say(f"{BOLD}Virtualenv{RESET}")

    if recreate:
        shutil.rmtree(install.venv, ignore_errors=True)

    if os.path.isdir(install.venv) and venv_is_usable(install):
        say(f"  {OK} reusing {DIM}{tilde(install.venv)}{RESET}")
    else:
        if os.path.isdir(install.venv):
            say(f"  {OPTIONAL} the existing venv no longer runs — rebuilding it")
            shutil.rmtree(install.venv, ignore_errors=True)
        python = base_python()
        say(f"  {DIM}creating from {tilde(python)}…{RESET}")
        try:
            done = subprocess.run([python, "-m", "venv", install.venv],
                                  capture_output=True, text=True, timeout=600)
        except (OSError, subprocess.SubprocessError) as err:
            say(f"  {MISSING} could not create it {DIM}— {err}{RESET}")
            return False
        if done.returncode != 0:
            say(f"  {MISSING} could not create it{RESET}")
            for line in done.stderr.strip().splitlines()[-4:]:
                say(f"    {DIM}{line}{RESET}")
            # Debian splits the venv module out of the interpreter package.
            if "ensurepip" in done.stderr or "venv" in done.stderr:
                family = distro_family()
                if family == "debian":
                    say(f"  {DIM}try: sudo apt install python3-venv{RESET}")
            return False
        say(f"  {OK} created {DIM}{tilde(install.venv)}{RESET}")
    return True


def sync_dependencies(install):
    """pip install the app's requirements into its venv. Returns False on failure."""
    requirements = os.path.join(install.app, "requirements.txt")
    say(f"  {DIM}installing dependencies (this can take a minute)…{RESET}")
    try:
        done = subprocess.run(
            [install.python, "-m", "pip", "install", "--disable-pip-version-check",
             "-r", requirements],
            capture_output=True, text=True, timeout=1800)
    except (OSError, subprocess.SubprocessError) as err:
        say(f"  {MISSING} pip failed {DIM}— {err}{RESET}")
        return False
    if done.returncode != 0:
        say(f"  {MISSING} pip could not install everything{RESET}")
        for line in done.stderr.strip().splitlines()[-6:]:
            say(f"    {DIM}{line}{RESET}")
        say(f"  {DIM}retry by hand: {tilde(install.python)} -m pip install -r "
            f"{tilde(requirements)}{RESET}")
        return False
    say(f"  {OK} dependencies installed {DIM}from requirements.txt{RESET}")
    return True


# --- Desktop integration ---------------------------------------------------
def launcher_script(install):
    """A tiny shell wrapper, so the app is also a command in the terminal."""
    return f"""#!/bin/sh
{LAUNCHER_MARK}
exec {shell_quote(install.python)} {shell_quote(install.entry_point)} "$@"
"""


def desktop_entry(install):
    """The .desktop file contents.

    StartupWMClass must equal the WM_CLASS the window actually carries, or the
    running app shows up as a second, nameless taskbar icon. gui.App passes
    APP_ID to Tk as its className; Tk capitalizes that into the class half of
    WM_CLASS, which is what desktops match on.
    """
    wm_class = APP_ID.capitalize()
    return f"""[Desktop Entry]
Type=Application
Version=1.0
Name={APP_NAME}
GenericName=Clip Manager
Comment=Browse, trim and share your game clips
Exec={shell_quote(LAUNCHER)}
Path={install.app}
Icon={APP_ID}
Terminal=false
Categories=AudioVideo;Video;Recorder;
Keywords=clips;recording;gameplay;moments;replay;
StartupNotify=true
StartupWMClass={wm_class}
"""


def shell_quote(path):
    """Quote a path for a command line (spaces are the norm in home folders).

    A leading ~ is left outside the quotes, because inside them the shell
    hands the program a literal tilde instead of the home directory.
    """
    if " " not in path:
        return path
    if path.startswith("~/"):
        return f'~/"{path[2:]}"'
    return f'"{path}"'


def install_launcher(install):
    """Write ~/.local/bin/vertex. Returns False if it could not be written."""
    if os.path.exists(LAUNCHER):
        try:
            with open(LAUNCHER) as handle:
                ours = LAUNCHER_MARK in handle.read()
        except OSError:
            ours = False
        if not ours:
            # Somebody else's file under our name: theirs, so it stays.
            say(f"  {OPTIONAL} {tilde(LAUNCHER)} exists and is not ours — left "
                f"alone{RESET}")
            return True
    try:
        os.makedirs(BIN_DIR, exist_ok=True)
        with open(LAUNCHER, "w") as handle:
            handle.write(launcher_script(install))
        os.chmod(LAUNCHER, 0o755)
    except OSError as err:
        say(f"  {MISSING} {tilde(LAUNCHER)} {DIM}— {err}{RESET}")
        return False
    say(f"  {OK} launcher {DIM}{tilde(LAUNCHER)}{RESET}")
    if BIN_DIR not in os.environ.get("PATH", "").split(os.pathsep):
        say(f"  {OPTIONAL} {tilde(BIN_DIR)} is not on your PATH {DIM}— the start "
            f"menu entry works regardless{RESET}")
    return True


def install_icons(install, variant):
    """Write the logo into the hicolor icon theme at the usual sizes."""
    try:
        from PIL import Image
    except ImportError:
        # Pillow is in the app's venv rather than this interpreter; borrow it.
        return install_icons_via(install.python, install, variant)
    return scale_icons(Image, install.logo(variant))


def install_icons_via(python, install, variant):
    """Scale the icons with the app's own interpreter, which has Pillow."""
    code = (
        "import os, sys\n"
        "from PIL import Image\n"
        "logo, root, sizes = sys.argv[1], sys.argv[2], [int(s) for s in sys.argv[3:]]\n"
        "with Image.open(logo) as src:\n"
        "    src = src.convert('RGBA')\n"
        "    for size in sizes:\n"
        "        target = os.path.join(root, f'{size}x{size}', 'apps')\n"
        "        os.makedirs(target, exist_ok=True)\n"
        f"        src.resize((size, size), Image.LANCZOS).save(os.path.join(target, '{APP_ID}.png'))\n"
    )
    logo = install.logo(variant)
    if not os.path.exists(logo):
        say(f"  {MISSING} icons {DIM}— {tilde(logo)} not found{RESET}")
        return False
    try:
        done = subprocess.run(
            [python, "-c", code, logo, ICON_ROOT, *[str(s) for s in ICON_SIZES]],
            capture_output=True, text=True, timeout=300)
    except (OSError, subprocess.SubprocessError) as err:
        say(f"  {MISSING} icons {DIM}— {err}{RESET}")
        return False
    if done.returncode != 0:
        lines = done.stderr.strip().splitlines()
        say(f"  {MISSING} icons {DIM}— {lines[-1] if lines else 'failed'}{RESET}")
        return False
    say(f"  {OK} icons {DIM}{variant} artwork · {tilde(ICON_ROOT)}/<size>/apps/"
        f"{APP_ID}.png{RESET}")
    return True


def scale_icons(Image, logo):
    """Write every icon size from `logo` using an already-imported Pillow."""
    if not os.path.exists(logo):
        say(f"  {MISSING} icons {DIM}— {tilde(logo)} not found{RESET}")
        return False
    try:
        with Image.open(logo) as source:
            source = source.convert("RGBA")
            for size in ICON_SIZES:
                target_dir = os.path.join(ICON_ROOT, f"{size}x{size}", "apps")
                os.makedirs(target_dir, exist_ok=True)
                source.resize((size, size), Image.LANCZOS).save(
                    os.path.join(target_dir, f"{APP_ID}.png"))
    except (OSError, ValueError) as err:
        say(f"  {MISSING} icons {DIM}— {err}{RESET}")
        return False
    say(f"  {OK} icons {DIM}{tilde(ICON_ROOT)}/<size>/apps/{APP_ID}.png{RESET}")
    return True


def registered_files(app_id):
    """Every file the desktop integration writes for `app_id`."""
    return [os.path.join(DESKTOP_DIR, f"{app_id}.desktop")] + [
        os.path.join(ICON_ROOT, f"{size}x{size}", "apps", f"{app_id}.png")
        for size in ICON_SIZES
    ]


def remove_files(paths, complain=True):
    """Delete `paths`, ignoring the ones that were never there. Returns a count."""
    removed = 0
    for path in paths:
        try:
            os.remove(path)
            removed += 1
        except FileNotFoundError:
            pass
        except OSError as err:
            if complain:
                say(f"  {MISSING} {tilde(path)} {DIM}— {err}{RESET}")
    return removed


def remove_legacy_entries():
    """Drop the entries and icons left by the app's previous names."""
    paths = [path for app_id in LEGACY_APP_IDS
             for path in registered_files(app_id)]
    removed = remove_files(paths, complain=False)
    if removed:
        say(f"  {OK} removed {removed} file(s) {DIM}from an earlier name of the "
            f"app{RESET}")


def refresh_desktop_caches():
    """Nudge the desktop into noticing the entry. Best-effort and silent.

    kbuildsycoca is the one that matters on KDE: Plasma's launcher reads its own
    ksycoca cache, so an entry that update-desktop-database has already indexed
    still will not appear in the menu until this runs.
    """
    for argv in (["update-desktop-database", DESKTOP_DIR],
                 ["gtk-update-icon-cache", "-f", "-t", ICON_ROOT],
                 ["kbuildsycoca6", "--noincremental"],
                 ["kbuildsycoca5", "--noincremental"]):
        if shutil.which(argv[0]) is None:
            continue
        try:
            subprocess.run(argv, capture_output=True, timeout=60, check=False)
        except (OSError, subprocess.SubprocessError):
            pass


def install_desktop(install, variant):
    """Install the launcher, start-menu entry and icons. Returns False on failure."""
    say()
    say(f"{BOLD}Desktop integration{RESET}")

    ok = install_launcher(install)
    ok = install_icons(install, variant) and ok
    try:
        os.makedirs(DESKTOP_DIR, exist_ok=True)
        with open(DESKTOP_FILE, "w") as handle:
            handle.write(desktop_entry(install))
        os.chmod(DESKTOP_FILE, 0o755)
    except OSError as err:
        say(f"  {MISSING} {tilde(DESKTOP_FILE)} {DIM}— {err}{RESET}")
        return False
    say(f"  {OK} start menu entry {DIM}{tilde(DESKTOP_FILE)}{RESET}")
    say(f"  {OK} launches {DIM}{tilde(install.python)} "
        f"{tilde(install.entry_point)}{RESET}")

    remove_legacy_entries()
    refresh_desktop_caches()
    return ok


def uninstall(install):
    """Remove the program. Everything the user made is deliberately kept."""
    say(f"{BOLD}Removing {APP_NAME}{RESET}")

    paths = registered_files(APP_ID)
    for app_id in LEGACY_APP_IDS:
        paths += registered_files(app_id)
    say(f"  {OK} removed {remove_files(paths)} desktop file(s)")

    if os.path.exists(LAUNCHER):
        try:
            with open(LAUNCHER) as handle:
                ours = LAUNCHER_MARK in handle.read()
        except OSError:
            ours = False
        if ours:
            remove_files([LAUNCHER])
            say(f"  {OK} removed {DIM}{tilde(LAUNCHER)}{RESET}")
        else:
            say(f"  {OPTIONAL} {tilde(LAUNCHER)} is not ours — left alone")

    # The manifest is what proves this directory is an install of ours. Without
    # it we do not recursively delete anything.
    if install.installed:
        try:
            shutil.rmtree(install.root)
            say(f"  {OK} removed {DIM}{tilde(install.root)}{RESET}")
        except OSError as err:
            say(f"  {MISSING} {tilde(install.root)} {DIM}— {err}{RESET}")
    elif os.path.isdir(install.root):
        say(f"  {OPTIONAL} {tilde(install.root)} has no install marker — left "
            f"alone{RESET}")
    else:
        say(f"  {DIM}nothing installed at {tilde(install.root)}{RESET}")

    refresh_desktop_caches()

    say()
    say(f"{BOLD}Kept{RESET}")
    say(f"  {DIM}your clips, exports, config, library and thumbnails are "
        f"untouched.{RESET}")
    config = read_config()
    # Only the app's own bookkeeping is offered up for deletion. Clips and
    # exports are the user's own video files — printing an rm for those, next
    # to lines meant to be pasted, is how somebody loses a library.
    kept = [CONFIG_DIR] + [os.path.expanduser(config[key])
                           for key in ("data_path", "state_path", "cache_path")
                           if config.get(key)]
    removable = [path for path in dict.fromkeys(kept) if os.path.exists(path)]
    if removable:
        say(f"  {DIM}to also drop the library, settings and thumbnails:{RESET}")
        for path in removable:
            say(f"    {DIM}rm -r {shell_quote(tilde(path))}{RESET}")
    say(f"  {DIM}your clips and exports are not listed — deleting those is never "
        f"part of uninstalling{RESET}")


# --- Config ----------------------------------------------------------------
def reset_config():
    """Move the current config aside so the next launch runs setup again."""
    say(f"{BOLD}Config{RESET}")
    if not os.path.exists(CONFIG_PATH):
        say(f"  {OK} no config yet — the next launch runs setup")
        return
    # Stamped rather than a plain .bak, so resetting twice does not overwrite
    # the first backup — the one that has the settings worth getting back.
    backup = f"{CONFIG_PATH}.{time.strftime('%Y%m%d-%H%M%S')}.bak"
    try:
        os.replace(CONFIG_PATH, backup)
    except OSError as err:
        say(f"  {MISSING} could not move it aside {DIM}— {err}{RESET}")
        return
    say(f"  {OK} moved to {tilde(backup)} — the next launch runs setup")
    say(f"  {DIM}your library is untouched; setup will find it again if you "
        f"point it at the same folders{RESET}")


def ensure_dirs(config):
    """Make sure the folders the app will write into exist.

    An existing config names its own — often still under an older slug — and
    those are the ones created. Only a fresh install falls back to the XDG
    defaults. Existing folders are left exactly as they are.
    """
    say()
    say(f"{BOLD}Directories{RESET}")
    wanted = [CONFIG_DIR]
    if config:
        wanted += [os.path.expanduser(config[key]) for key in
                   ("data_path", "state_path", "cache_path") if config.get(key)]
    else:
        wanted += XDG_DIRS[1:]

    ok = True
    for path in dict.fromkeys(wanted):
        try:
            existed = os.path.isdir(path)
            os.makedirs(path, exist_ok=True)
            say(f"  {OK} {tilde(path)}" +
                (f" {DIM}(already there){RESET}" if existed else f" {DIM}(created){RESET}"))
        except OSError as err:
            ok = False
            say(f"  {MISSING} {tilde(path)} {DIM}— {err}{RESET}")
    return ok


def describe_first_run(install):
    """Show what the first-run screen will propose, without writing anything."""
    say()
    say(f"{BOLD}First launch{RESET}")
    say(f"  {DIM}Setup opens automatically and suggests these, derived from "
        f"your account:{RESET}")
    code = (
        "import sys\n"
        "sys.path.insert(0, sys.argv[1])\n"
        "import core\n"
        "d = core.default_config()\n"
        "print('\\n'.join(f'{k}\\t{getattr(d, k)}' for k in core.REQUIRED_FIELDS))\n"
    )
    try:
        done = subprocess.run([install.python, "-c", code,
                               os.path.join(install.app, "src")],
                              capture_output=True, text=True, timeout=120)
    except (OSError, subprocess.SubprocessError) as err:
        say(f"  {OPTIONAL} could not preview the defaults {DIM}— {err}{RESET}")
        return
    if done.returncode != 0:
        lines = done.stderr.strip().splitlines()
        say(f"  {OPTIONAL} could not preview the defaults {DIM}— "
            f"{lines[-1] if lines else 'failed'}{RESET}")
        return
    # Folders only: setup's later steps (audio devices, importing an existing
    # library) have nothing to derive from the account, so there is nothing to
    # preview for them here.
    for line in done.stdout.strip().splitlines():
        key, _, value = line.partition("\t")
        say(f"    {key:<12} {value}")


# --- Entry point -----------------------------------------------------------
def build_parser():
    parser = argparse.ArgumentParser(
        description=f"Install {APP_NAME} into a permanent location.")
    parser.add_argument("--check", action="store_true",
                        help="only report on the requirements, change nothing")
    parser.add_argument("--uninstall", action="store_true",
                        help="remove the program, keeping every file you made")
    parser.add_argument("--reset-config", action="store_true",
                        help="run first-run setup again on the next launch")
    parser.add_argument("--prefix", default=DEFAULT_PREFIX, metavar="DIR",
                        help=f"where to install (default: {tilde(DEFAULT_PREFIX)})")
    parser.add_argument("--no-venv", action="store_true",
                        help="use the interpreter running this script instead "
                             "of giving the app its own virtualenv")
    parser.add_argument("--recreate-venv", action="store_true",
                        help="rebuild the app's virtualenv from scratch")
    parser.add_argument("--no-desktop", action="store_true",
                        help="skip the launcher, start menu entry and icons")
    parser.add_argument("--icon", choices=("light", "dark"), default="light",
                        help="which ink the start-menu icon is drawn in: light "
                             "for a dark panel (the default), dark for a light "
                             "one")
    return parser


def main():
    args = build_parser().parse_args()

    install = Install(root=os.path.abspath(os.path.expanduser(
                          os.path.join(args.prefix, APP_ID))),
                      use_venv=not args.no_venv)

    say(f"{BOLD}{APP_NAME}{RESET}")
    say(f"  {DIM}source  {tilde(HERE)}{RESET}")
    say(f"  {DIM}install {tilde(install.root)}{RESET}")
    say()

    if args.uninstall:
        uninstall(install)
        return 0

    config = read_config()

    # Pre-flight: the version, then the things pip cannot supply.
    say(f"{BOLD}Interpreter{RESET}")
    py_ok = check_python()
    say()
    family = distro_family()
    missing_system, missing_optional = check_requirements(
        SYSTEM_REQUIREMENTS, heading="System requirements")
    report_fixes(missing_system + missing_optional, family)

    # Anything already installed is reported against the app's own interpreter,
    # since that is what a launch will use.
    if install.installed and os.path.exists(install.python):
        say()
        check_requirements(PIP_REQUIREMENTS, python=install.python,
                           heading="Python packages (installed)")
    else:
        say()
        say(f"{BOLD}Python packages{RESET}")
        for req in PIP_REQUIREMENTS:
            say(f"  {OPTIONAL} {req.pip} {DIM}— will be installed into the app's "
                f"virtualenv{RESET}")

    report_user_data(config)

    if args.check:
        say()
        if missing_system or not py_ok:
            say(f"{MISSING} Missing required components — see above.")
            return 1
        say("Nothing was changed (--check).")
        return 0

    if not py_ok or missing_system:
        say()
        say(f"{MISSING} {BOLD}Install the missing components above, then run "
            f"this again.{RESET}")
        return 1

    problem = guard_paths(install, config)
    if problem:
        say()
        say(f"{MISSING} {BOLD}Refusing to install:{RESET} {problem}.")
        say(f"  {DIM}pick somewhere else with --prefix DIR{RESET}")
        return 1

    absent = check_payload()
    if absent:
        say()
        say(f"{MISSING} {BOLD}The checkout is incomplete:{RESET} "
            f"{', '.join(absent)} not found in {tilde(HERE)}.")
        return 1

    if not install_payload(install):
        return 1

    if install.use_venv:
        if not build_venv(install, recreate=args.recreate_venv):
            return 1
        if not sync_dependencies(install):
            return 1
        say()
        missing_pip, _ = check_requirements(PIP_REQUIREMENTS, python=install.python,
                                            heading="Verifying")
        if missing_pip:
            say()
            say(f"{MISSING} {BOLD}The app's virtualenv is missing "
                f"{', '.join(req.label for req in missing_pip)}.{RESET}")
            return 1
    else:
        install.external_python = sys.executable
        if os.path.abspath(sys.executable).startswith(HERE + os.sep):
            say()
            say(f"{MISSING} {BOLD}--no-venv with an interpreter inside the "
                f"checkout.{RESET}")
            say(f"  {DIM}{tilde(sys.executable)} disappears with the clone, "
                f"which is the breakage this install is meant to avoid. Drop "
                f"--no-venv, or run this with a python from outside "
                f"{tilde(HERE)}.{RESET}")
            return 1
        say()
        missing_pip, _ = check_requirements(PIP_REQUIREMENTS, python=install.python,
                                            heading="Verifying")
        if missing_pip:
            say()
            say(f"{MISSING} {BOLD}Install these into {tilde(install.python)} "
                f"first:{RESET}")
            say(f"  {tilde(install.python)} -m pip install "
                f"{' '.join(req.pip for req in missing_pip)}")
            return 1

    write_manifest(install)

    ok = ensure_dirs(config)
    if args.reset_config:
        say()
        reset_config()
    if not args.no_desktop:
        ok = install_desktop(install, args.icon) and ok
    if not config:
        describe_first_run(install)

    say()
    if ok:
        how = (f"Look for “{APP_NAME}” in your start menu, or run: {APP_ID}"
               if not args.no_desktop else
               f"Run it with: {shell_quote(tilde(install.python))} "
               f"{shell_quote(tilde(install.entry_point))}")
        say(f"{OK} {BOLD}Installed.{RESET} {how}")
        say(f"  {DIM}The app runs from {tilde(install.app)} — the checkout at "
            f"{tilde(HERE)} is no longer needed.{RESET}")
        say(f"  {DIM}Pull an update and run this again to upgrade in place.{RESET}")
    else:
        say(f"{OPTIONAL} Finished with warnings — see above.")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
